services:
  - type: worker
    name: telefeed-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
    region: oregon
    branch: main
    rootDir: .
    scaling:
      numInstances: 1